# ================================
# Inventory Group: group name "servers"
# ================================
[servers]
worker-node-01 ansible_host=54.82.42.164 ansible_user=ubuntu
worker-node-02 ansible_host=3.90.203.247 ansible_user=ec2-user


# ================================
# Global Variables for All Servers
# ================================
[all:vars]

# Private SSH Key Path
ansible_ssh_private_key_file=/home/ubuntu/.ssh/id_ed25519

# Python Interpreter Path
ansible_python_interpreter=/usr/bin/python3

# Disable SSH host key verification prompt
ansible_host_key_checking=false